package kz.app.appclient;

import kz.app.appclient.service.ClientDao;
import kz.app.appcore.model.DbRec;
import kz.app.appcore.utils.UtCnv;
import kz.app.appcore.utils.UtDb;
import kz.app.appdata.service.UtEntityData;
import kz.app.appdbtools.repository.Db;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

@SpringBootTest
public class AppClientTest {

    @Autowired
    Db db;

    @Autowired
    ClientDao clientDao;

    @Test
    public void testLoad() throws Exception {
        List<DbRec> res = clientDao.loadClient(0);
        UtDb.outTable(res);
    }

    @Test
    public void testSave_ins() throws Exception {
        DbRec map = new DbRec();
        map.put("name", "Test Save");
        map.put("BIN", "1241414494");
        map.put("ContactPerson", "Фамилия И.О");
        map.put("ContactDetails", "г. Астана, ул. 45б, офис 11, тел. 85-858-85");
        map.put("Description", "test 01");
        List<DbRec> res = clientDao.saveClient("ins", map);
        UtDb.outTable(res);
    }

    @Test
    public void testInsertEntity() throws Exception {
        DbRec map = new DbRec();
        for (int idx = 1; idx <= 3; idx++) {
            map.put("name", "AAA " + idx);
            List<DbRec> res = clientDao.saveClient("ins", map);
            UtDb.outTable(res);
        }
    }

    @Test
    public void testUpdateEntity() throws Exception {
        DbRec map = new DbRec();
        map.put("id", 1011);

        map.put("name", "AAA");
        map.put("fullname", "AAA AAA AAA");
        map.put("cmt", "version 1 ");
        map.put("cmtVer", "Version 2");
        List<DbRec> res = clientDao.saveClient("upd", map);
        UtDb.outTable(res);
    }



    @Test
    public void testDelete() throws Exception {
        clientDao.deleteClientWithProps(1013);
    }

    @Test
    public void testInsert() throws Exception {
        List<DbRec> res = db.loadList("ObjVer", null);
        UtDb.outTable(res);

        long idValue = 777666;
        long id = db.insertRec("ObjVer", UtCnv.toMap("id", idValue, "name", "name" + idValue));
        System.out.println("id: " + id);

        long id1 = db.insertRec("ObjVer", UtCnv.toMap("name", "name1"));
        System.out.println("id1: " + id1);

        res = db.loadList("ObjVer", null);
        UtDb.outTable(res);
    }


    @Test
    public void testSetEntity() throws Exception {
        List<DbRec> res = db.loadSql("select table_name " +
                "from information_schema.tables t " +
                "where table_schema='public'", null);


        for (DbRec rec : res) {
            String nm = rec.getString("table_name");

            UtEntityData ue = new UtEntityData(db, nm);
            long id = ue.getNextId(nm);

            db.execSql("alter table "+ nm + " alter column id add generated by default as identity (start with "+id + ")", null);
        }
    }


}
