package kz.app.appmain;

import kz.app.appcore.model.DbRec;
import kz.app.appcore.utils.UtCnv;
import kz.app.appcore.utils.UtDb;
import kz.app.appcore.utils.UtFile;
import kz.app.appdbtools.repository.Db;
import kz.app.appmain.service.DictDao;
import kz.app.appstorage.repository.StorageRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.Random;

@SpringBootTest
class AppTest {

    @Autowired
    private DictDao dictDao;

    @Autowired
    private Db db;

    @Autowired
    @Qualifier("appDb")
    private Db dbApp;

    @Autowired
    @Qualifier("contentStorage")
    private StorageRepository storageRepository;

    Random rnd = new Random();

    @Test
    void list() throws Exception {
        List<DbRec> list = db.loadList("Dict", null);
        UtDb.outTable(list);
    }

    @Test
    void listDbApp() throws Exception {
        dbApp.execSql(sqlCreate(), null);

        db.insertRec("Dict", UtCnv.toMap("name", "value-db-" + rnd.nextInt(10000)));
        dbApp.insertRec("Dict", UtCnv.toMap("name", "value-dbApp-" + rnd.nextInt(10000)));

        List<DbRec> list1 = db.loadList("Dict", null);
        List<DbRec> list2 = dbApp.loadList("Dict", null);

        System.out.println("Db");
        UtDb.outTable(list1);
        System.out.println();

        System.out.println("DbApp");
        UtDb.outTable(list2);
    }

    private String sqlCreate() {
        return """
                create table if not exists Dict (
                    id   bigint generated by default as identity
                         constraint dict_pkey primary key,
                    name varchar(255) not null
                )
                """;
    }

    @Test
    void createDict() throws Exception {
        long id = db.insertRec("Dict", Map.of("name", "AttributeType"));
        System.out.println("Dict.id: " + id);

        List<DbRec> list = db.loadList("Dict", null);
        UtDb.outTable(list);
    }

    @Test
    void loadDict() throws Exception {
        List<DbRec> list = dictDao.loadDict("AttributeType");
        UtDb.outTable(list);
    }


    String fileHash = "8004928d7a4e";
    String fileName = "src/test/java/kz/app/appmain/appTest-001.txt";

    @Test
    void uploadFile() throws Exception {
        File file = new File(fileName);

        System.out.println("file: " + file);
        System.out.println(UtFile.loadString(file.getAbsolutePath()));

        storageRepository.uploadFile(file, fileHash);
        System.out.println("uploadFile, fileHash: " + fileHash);
    }

    @Test
    void downloadFile() throws Exception {
        uploadFile();

        //
        File file = storageRepository.downloadFile(fileHash);
        System.out.println("file: " + file);
        System.out.println(UtFile.loadString(file));

        //
        storageRepository.deleteFile(fileHash);
        System.out.println("deleteFile, fileHash: " + fileHash);

        //
        file = storageRepository.downloadFile(fileHash);
        System.out.println("file: " + file);
    }

}