#!/bin/bash
set -e  



# Check if Redis is running
if [ ! -f /usr/bin/redis-cli ]
then
  echo
  echo "Установка Redis-клиента"
  if [[ "$(uname)" == "Darwin" ]]; then
    brew install redis-cli
  else
    apt install redis-tools
  fi
else
  echo
  echo "Redis-клиент уже установлен"
fi

echo "Checking Redis status..."
if ! redis-cli ping > /dev/null 2>&1; then
  echo "Redis is not running. Please start Redis first."
  exit 1
fi



# Flush all Redis databases
echo "Flushing all Redis databases..."
redis-cli FLUSHALL
echo "Redis flushed successfully."



# Verify Redis is empty
echo "Verifying Redis is empty..."
KEYS_COUNT=$(redis-cli DBSIZE)
if [ "$KEYS_COUNT" -eq 0 ]; then
  echo "Redis is now empty."
else
  echo "Redis still contains data. Something went wrong!"
  exit 1
fi
