#!/bin/bash
set -e

if [ -f "bot-info.txt" ]; then
  echo ""
  echo "adding bot info"


  docker cp add-bot-info.sql db_files:/home/add-bot-info.sql

  token=$(grep "^token:" bot-info.txt | tr -d '\r' | awk '{print $2}')
  username=$(grep "^username:" bot-info.txt | tr -d '\r' | awk '{print $2}')

  docker exec db_files psql -U kis_smart_catalog -h localhost -p 5432 -a \
    --set ON_ERROR_STOP=on --set token="$token" --set username="$username" \
    -f /home/add-bot-info.sql
fi