#!/bin/bash

export PROVIDER_NAME="LDAP_AD"

export GROUP_NAME="LDAP_GROUPS"

export URL="ldap://192.168.0.6"

export USERS_DN="DC=kazinfosystems,DC=kz"

export GROUP_DN="DC=kazinfosystems,DC=kz"

export LOGIN="batman@kazinfosystems.kz"

export PASSWORD="Axario09S"

export ACCESS_TOKEN=$(curl -s --data "client_id=admin-cli" --data "username=smart_catalog" --data "password=Grpn404tfgNbp09we21" --data "grant_type=password" http://localhost:8282/realms/master/protocol/openid-connect/token | jq -r .access_token)

if [ -z "$ACCESS_TOKEN" ]; then
  echo "ACCESS_TOKEN is empty" >&2
  exit 1
fi

export RESULT=$(curl -X DELETE "http://localhost:8282/admin/realms/master/components/Ld6R3o3pT_64Kr9Nk3m8yQ" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $ACCESS_TOKEN")

export REALM_ID=$(curl -X GET "http://localhost:8282/admin/realms" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $ACCESS_TOKEN" | jq -r '.[] | select(.realm == "master") | .id')

echo $REALM_ID

export RESULT=$(curl -X POST "http://localhost:8282/admin/realms/master/components" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $ACCESS_TOKEN" \
     -d '{
  "id": "Ld6R3o3pT_64Kr9Nk3m8yQ",
  "name": "'$PROVIDER_NAME'",
  "parentId": "'$REALM_ID'",
  "providerId": "ldap",
  "providerType": "org.keycloak.storage.UserStorageProvider",
  "config": {
    "enabled": ["true"],
    "priority": ["0"],
    "importEnabled": ["true"],
    "editMode": ["UNSYNCED"],
    "syncRegistrations": ["false"],
    "vendor": ["Active Directory"],
    "usernameLDAPAttribute": ["sAMAccountName"],
    "rdnLDAPAttribute": ["cn"],
    "uuidLDAPAttribute": ["objectGUID"],
    "userObjectClasses": ["person, organizationalPerson, user"],
    "connectionUrl": ["'$URL'"],
    "usersDn": ["'$USERS_DN'"],
    "bindDn": ["'$LOGIN'"],
    "bindCredential": ["'$PASSWORD'"],
    "useTruststoreSpi": ["ldapsOnly"],
    "connectionPooling": ["true"],
    "pagination": ["true"],
    "allowKerberosAuthentication": ["false"],
    "batchSizeForSync": ["1000"],
    "fullSyncPeriod": ["3600"],
    "changedSyncPeriod": ["600"],
    "searchScope": ["2"],
    "customUserSearchFilter": ["(cn=*)"]
  }
}'
)

export RESULT=$(curl -X POST "http://localhost:8282/admin/realms/master/components" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $ACCESS_TOKEN" \
     -d '{
        "id": "6ed33a0f-bab1-4c15-9762-483f701a677c",
        "name": "'$GROUP_NAME'",
        "providerId": "group-ldap-mapper",
        "providerType": "org.keycloak.storage.ldap.mappers.LDAPStorageMapper",
        "parentId": "Ld6R3o3pT_64Kr9Nk3m8yQ",
        "config": {
            "membership.attribute.type": [
                "DN"
            ],
            "group.name.ldap.attribute": [
                "cn"
            ],
            "preserve.group.inheritance": [
                "false"
            ],
            "membership.user.ldap.attribute": [
                "cn"
            ],
            "groups.dn": [
                "'$GROUP_DN'"
            ],
            "mapped.group.attributes": [
                "MemberOf"
            ],
            "mode": [
                "READ_ONLY"
            ],
            "user.roles.retrieve.strategy": [
                "GET_GROUPS_FROM_USER_MEMBEROF_ATTRIBUTE"
            ],
            "membership.ldap.attribute": [
                "MemberOf"
            ],
            "ignore.missing.groups": [
                "false"
            ],
            "memberof.ldap.attribute": [
                "MemberOf"
            ],
            "group.object.classes": [
                "group"
            ],
            "groups.path": [
                "/"
            ],
            "drop.non.existing.groups.during.sync": [
                "false"
            ],
        }
    }'
)